export function getUserRatings() {
  try {
    return JSON.parse(localStorage.getItem('gcg_card_ratings') || '{}');
  } catch {
    return {};
  }
}

export function saveUserRatings(ratings) {
  localStorage.setItem('gcg_card_ratings', JSON.stringify(ratings));
}

// Score = sum of user ratings weighted by copy count
export function calculateDeckScore(chars, actions, ratings) {
  const all = [...chars, ...actions];
  const counts = {};
  all.forEach(id => { counts[id] = (counts[id] || 0) + 1; });
  return Object.entries(counts).reduce((sum, [id, count]) => {
    return sum + (ratings[id] || 0) * count;
  }, 0);
}

export function getMetaAnalytics(metaDecks) {
  const charCount = {};
  const actionCount = {};
  for (const deck of metaDecks) {
    for (const c of (deck.characters || [])) {
      charCount[c] = (charCount[c] || 0) + 1;
    }
    const seen = new Set();
    for (const a of (deck.actions || [])) {
      if (!seen.has(a)) {
        actionCount[a] = (actionCount[a] || 0) + 1;
        seen.add(a);
      }
    }
  }
  return { charCount, actionCount };
}

// Auto-generate deck based on ratings
export function autoGenerateDeck(cards, ratings) {
  const cardList = Object.values(cards);
  const getRating = (id) => ratings[id] || 0;

  // Top 3 characters by rating
  const chars = cardList
    .filter(c => c.type === 'character')
    .sort((a, b) => getRating(b.id) - getRating(a.id))
    .slice(0, 3)
    .map(c => c.id);

  // Get char name suffixes for talent matching
  const charIconSuffixes = chars.map(id => {
    const c = cards[id];
    return c?.icon_name?.replace('UI_Gcg_CardFace_Char_Avatar_', '') || '';
  });

  // Prioritise talents for selected characters
  const selectedTalents = cardList
    .filter(c => c.type === 'talent' && charIconSuffixes.some(s => c.icon_name?.includes(s)))
    .map(c => c.id);

  // All non-character action cards sorted by rating
  const actionCandidates = cardList
    .filter(c => c.type !== 'character')
    .sort((a, b) => getRating(b.id) - getRating(a.id));

  const actions = [];
  const countMap = {};

  // First add selected talents (up to 2 each)
  for (const id of selectedTalents) {
    if (actions.length >= 30) break;
    if ((countMap[id] || 0) < 2) {
      actions.push(id);
      countMap[id] = (countMap[id] || 0) + 1;
    }
    if (actions.length < 30 && (countMap[id] || 0) < 2) {
      actions.push(id);
      countMap[id] = (countMap[id] || 0) + 1;
    }
  }

  // Then fill with top-rated action cards
  for (const card of actionCandidates) {
    if (actions.length >= 30) break;
    const id = card.id;
    while ((countMap[id] || 0) < 2 && actions.length < 30) {
      actions.push(id);
      countMap[id] = (countMap[id] || 0) + 1;
    }
  }

  return { chars, actions };
}