import React,{useState,useCallback,useMemo,useEffect,useRef} from 'react';
import {Wand2,Save,FolderOpen,Trash2,ChevronLeft,ChevronRight,Plus,Minus,Layers,List,X,Zap} from 'lucide-react';
import {autoGenerateDeck,calcCardScore,getActiveComboDetails,isLegendCard,isGensoHenkan} from '../utils/tagScoring';
import {loadPresets,savePresets} from '../utils/storage';

const COST_JP={GCG_COST_DICE_CRYO:'氷',GCG_COST_DICE_HYDRO:'水',GCG_COST_DICE_PYRO:'炎',
  GCG_COST_DICE_ELECTRO:'雷',GCG_COST_DICE_ANEMO:'風',GCG_COST_DICE_GEO:'岩',
  GCG_COST_DICE_DENDRO:'草',GCG_COST_DICE_SAME:'同一',GCG_COST_DICE_VOID:'無色',
  GCG_COST_LEGEND:'秘伝'};
const EC={氷:'#93c5fd',水:'#60a5fa',炎:'#f87171',雷:'#c084fc',風:'#34d399',岩:'#fbbf24',草:'#4ade80',無色:'#94a3b8'};
const TL={character:'キャラ',weapon:'武器',artifact:'聖遺物',talent:'天賦',support:'サポート',event:'イベント'};
const TC={character:'#f87171',weapon:'#60a5fa',artifact:'#c084fc',talent:'#fbbf24',support:'#34d399',event:'#94a3b8'};
const TF=['all','character','weapon','artifact','talent','support','event'];
const EF=['all','氷','水','炎','雷','風','岩','草','無色'];

function fmtCost(cost){
  if(!cost||cost===null) return 'なし';
  if(typeof cost==='number') return `${cost}`;
  if(Array.isArray(cost)){
    const p=cost.filter(c=>c.cost_type!=='GCG_COST_INVALID'&&c.count)
      .map(c=>`${COST_JP[c.cost_type]||c.cost_type}×${c.count}`);
    return p.join('+')||'なし';
  }
  return 'なし';
}

// ── Tooltip ───────────────────────────────────────────────────────────────────
function CardTooltip({card,mousePos,cardTags,tags,tagCombos}){
  if(!card) return null;
  const myTags=cardTags[card.id]||[];
  const s=calcCardScore(card.id,cardTags,tags,tagCombos);
  const ec=EC[card.element]||'#94a3b8';
  const W=260,H=300;
  let left=mousePos.x+16,top=mousePos.y-50;
  if(left+W>window.innerWidth-8) left=mousePos.x-W-8;
  if(top+H>window.innerHeight-8) top=window.innerHeight-H-8;
  if(top<8) top=8;
  // Show legend / 元素変幻 badge
  const legend=isLegendCard(card);
  const gh=isGensoHenkan(card);
  return(
    <div className={`card-tooltip ${card?'active':''}`} style={{left,top}}>
      <div className="tooltip-header" style={{borderBottomColor:ec+'55'}}>
        <img src={card.url} alt={card.name} className="tooltip-img"
          onError={e=>{e.target.style.display='none';}}/>
        <div className="tooltip-title">
          <span className="tooltip-name">{card.name}</span>
          <div className="tooltip-badges">
            <span className="tooltip-badge" style={{color:TC[card.type],borderColor:TC[card.type]+'55'}}>{TL[card.type]}</span>
            <span className="tooltip-badge" style={{color:ec,borderColor:ec+'55'}}>{card.element}</span>
            {legend&&<span className="tooltip-badge" style={{color:'#fbbf24',borderColor:'#fbbf2455'}}>秘伝</span>}
            {gh&&<span className="tooltip-badge" style={{color:'#c084fc',borderColor:'#c084fc55'}}>元素変幻</span>}
          </div>
        </div>
      </div>
      <div className="tooltip-stats">
        {card.type==='character'&&<div className="tooltip-stat-row"><span className="tooltip-stat-label">HP</span><span style={{color:'#f87171'}}>♥ {card.hp}</span></div>}
        <div className="tooltip-stat-row"><span className="tooltip-stat-label">コスト</span><span>{fmtCost(card.cost)}</span></div>
        {myTags.length>0&&<div className="tooltip-stat-row"><span className="tooltip-stat-label">タグ</span><span style={{fontSize:'.75rem'}}>{[...new Set(myTags)].map(t=>`${t}${myTags.filter(x=>x===t).length>1?`×${myTags.filter(x=>x===t).length}`:''}`).join(' / ')}</span></div>}
        {s!==0&&<div className="tooltip-stat-row"><span className="tooltip-stat-label">スコア</span><span style={{color:s>0?'#34d399':'#f87171',fontWeight:700}}>{s>0?`+${s}`:s}</span></div>}
      </div>
      {card.desc&&<p className="tooltip-desc">{card.desc.replace(/\\n/g,' ')}</p>}
      <div className="tooltip-hint"><span>タップ: 追加・削除</span><br/><span>長押しドラッグ: プレビュー</span></div>
    </div>
  );
}

// ── TcgCard ───────────────────────────────────────────────────────────────────
function TcgCard({card,count,onAdd,onRemove,onHover,onLeave,onMouseMove,onTouchStart,isMaxed,isLimited}){
  const ec=EC[card.element]||'#94a3b8';
  return(
    <div className={`tcg-card ${count>0?'selected':''} ${isMaxed||isLimited?'maxed':''}`}
      data-card-id={card.id}
      onClick={()=>onAdd(card)}
      onContextMenu={e=>{e.preventDefault();onRemove(card);}}
      onMouseEnter={()=>onHover(card)} onMouseLeave={onLeave} onMouseMove={onMouseMove}
      onTouchStart={e=>onTouchStart(card.id, e)}>
      <div className="card-elem-strip" style={{background:ec}}/>
      <img src={card.url} alt={card.name} className="card-img" loading="lazy"
        onError={e=>{e.target.style.background='#1e293b';e.target.src='';}}/>
      <span className="card-name">{card.name}</span>
      {count>0&&<span className="card-badge">×{count}</span>}
      {isLegendCard(card)&&<span className="card-legend-badge">秘</span>}
    </div>
  );
}

// ── CharSlot ──────────────────────────────────────────────────────────────────
function CharSlot({card,onHover,onLeave,onMouseMove,onTouchStart,onRemove}){
  if(!card) return(<div className="deck-slot empty"><span>＋</span><small>キャラ</small></div>);
  const ec=EC[card.element]||'#94a3b8';
  return(
    <div className="deck-slot filled" style={{borderColor:ec+'99'}}
      data-card-id={card.id}
      onMouseEnter={()=>onHover(card)} onMouseLeave={onLeave} onMouseMove={onMouseMove}
      onTouchStart={e=>onTouchStart(card.id, e)}
      onClick={()=>onRemove(card)} onContextMenu={e=>{e.preventDefault();onRemove(card);}}>
      <img src={card.url} alt={card.name} onError={e=>{e.target.style.display='none';}}/>
      <div className="slot-overlay">
        <span className="slot-name">{card.name}</span>
        <span className="slot-elem" style={{color:ec}}>{card.element}</span>
        <span className="slot-hp">♥ {card.hp}</span>
      </div>
    </div>
  );
}

// ── ActionRow ─────────────────────────────────────────────────────────────────
function ActionRow({card,count,onAdd,onRemove,onHover,onLeave,onMouseMove,onTouchStart,cardTags,tags,tagCombos}){
  const s=calcCardScore(card.id,cardTags,tags,tagCombos);
  return(
    <div className="action-row"
      data-card-id={card.id}
      onMouseEnter={()=>onHover(card)} onMouseLeave={onLeave} onMouseMove={onMouseMove}
      onTouchStart={e=>onTouchStart(card.id, e)}>
      <img src={card.url} alt="" className="action-thumb" onError={e=>{e.target.style.visibility='hidden';}}/>
      <span className="action-name" onClick={()=>onAdd(card)}>{card.name}</span>
      {s!==0&&<span className="action-rating" style={{color:s>0?'#34d399':'#f87171'}}>{s>0?`+${s}`:s}</span>}
      <div className="action-controls">
        <button className="btn-icon" onClick={()=>onRemove(card)}><Minus size={13}/></button>
        <span className="action-count">×{count}</span>
        <button className="btn-icon" onClick={()=>onAdd(card)} disabled={count>=2}><Plus size={13}/></button>
      </div>
    </div>
  );
}

// ── PresetModal ───────────────────────────────────────────────────────────────
function PresetModal({onClose,selectedChars,selectedActions,score,onLoad}){
  const [presets,setPresets]=useState(()=>loadPresets());
  const [name,setName]=useState('');
  const save=()=>{
    if(!name.trim()) return;
    const p={id:Date.now().toString(),name:name.trim(),chars:[...selectedChars],actions:[...selectedActions],score,date:new Date().toLocaleDateString('ja-JP')};
    const updated=[p,...presets].slice(0,20);
    setPresets(updated); savePresets(updated); setName('');
  };
  const del=id=>{ const u=presets.filter(p=>p.id!==id); setPresets(u); savePresets(u); };
  return(
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-box glass-panel" onClick={e=>e.stopPropagation()}>
        <div className="modal-header">
          <h3>プリセット</h3>
          <button className="btn-icon" onClick={onClose}><X size={18}/></button>
        </div>
        <div className="preset-save-row">
          <input className="preset-name-input" placeholder="デッキ名..."
            value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&save()}/>
          <button className="import-btn" onClick={save} disabled={!name.trim()}><Save size={13}/> 保存</button>
        </div>
        <div className="preset-list">
          {presets.length===0&&<p className="empty-msg">保存なし</p>}
          {presets.map(p=>(
            <div key={p.id} className="preset-item">
              <div className="preset-info">
                <span className="preset-name">{p.name}</span>
                <span className="preset-meta">スコア {p.score>0?'+':''}{p.score} · {p.date}</span>
              </div>
              <div className="preset-actions">
                <button className="btn-icon" onClick={()=>{onLoad(p);onClose();}}><FolderOpen size={13}/></button>
                <button className="btn-icon danger" onClick={()=>del(p.id)}><Trash2 size={13}/></button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ── Deck constraint helpers ───────────────────────────────────────────────────
function countLegend(ids,cards){ return ids.filter(id=>isLegendCard(cards[id])).length; }
function countGH(ids,cards){ return ids.filter(id=>isGensoHenkan(cards[id])).length; }

// ── Dynamic page size ─────────────────────────────────────────────────────────
function usePageSize(){
  const [ps,setPs]=useState(()=>{
    const w=window.innerWidth;
    if(w<480) return 20; if(w<768) return 30; return 48;
  });
  useEffect(()=>{
    const h=()=>{ const w=window.innerWidth; setPs(w<480?20:w<768?30:48); };
    window.addEventListener('resize',h);
    return()=>window.removeEventListener('resize',h);
  },[]);
  return ps;
}

// ── Main DeckBuilder ──────────────────────────────────────────────────────────
export default function DeckBuilder({
  cards,selectedChars,setSelectedChars,selectedActions,setSelectedActions,
  score,cardTags,tags,tagCombos,
}){
  const PAGE_SIZE=usePageSize();
  const [typeFilter,setTF]=useState('all');
  const [elemFilter,setEF]=useState('all');
  const [search,setSearch]=useState('');
  const [page,setPage]=useState(0);
  const [hovered,setHovered]=useState(null);
  const longPressTimer = useRef(null);
  const [isMobilePreview, setIsMobilePreview] = useState(false);

  const handleMM=useCallback(e=>setMP({x:e.clientX,y:e.clientY}),[]);

  // ── Mobile Touch Preview Logic ──────────────────────────────────────────────
  const handleTouchStart = useCallback((id, e) => {
    const touch = e.touches[0];
    const x = touch.clientX;
    const y = touch.clientY;
    setMP({ x, y });
    
    // Start long press timer
    longPressTimer.current = setTimeout(() => {
      setIsMobilePreview(true);
      const el = document.elementFromPoint(x, y);
      const cardId = el?.closest('[data-card-id]')?.dataset.cardId;
      if (cardId && cards[cardId]) {
        setHovered(cards[cardId]);
      }
    }, 150);
  }, [cards]);

  const handleTouchMove = useCallback((e) => {
    const touch = e.touches[0];
    const x = touch.clientX;
    const y = touch.clientY;
    setMP({ x, y });
    
    if (isMobilePreview) {
      const el = document.elementFromPoint(x, y);
      const cardId = el?.closest('[data-card-id]')?.dataset.cardId;
      if (cardId && cards[cardId]) {
        setHovered(cards[cardId]);
      } else {
        setHovered(null);
      }
    }
  }, [isMobilePreview, cards]);

  const handleTouchEnd = useCallback(() => {
    clearTimeout(longPressTimer.current);
    setIsMobilePreview(false);
    setHovered(null);
  }, []);

  const filtered=useMemo(()=>Object.values(cards).filter(c=>{
    if(typeFilter!=='all'&&c.type!==typeFilter) return false;
    if(elemFilter!=='all'&&c.element!==elemFilter) return false;
    if(search&&!c.name.includes(search)) return false;
    return true;
  }),[cards,typeFilter,elemFilter,search]);

  const totalPages=Math.ceil(filtered.length/PAGE_SIZE);
  const pageCards=filtered.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);

  const acm=useMemo(()=>{ const m={}; selectedActions.forEach(id=>{m[id]=(m[id]||0)+1;}); return m; },[selectedActions]);
  const charCount=selectedChars.length;
  const actionCount=selectedActions.length;
  const allDeckIds=[...selectedChars,...selectedActions];
  const legendCount=useMemo(()=>countLegend(allDeckIds,cards),[allDeckIds,cards]);
  const ghCount=useMemo(()=>countGH(allDeckIds,cards),[allDeckIds,cards]);

  const showLimit=(msg)=>{ setLimitMsg(msg); setTimeout(()=>setLimitMsg(''),2500); };

  const addCard=useCallback((card)=>{
    if(card.type==='character'){
      if(charCount>=3||selectedChars.includes(card.id)) return;
      setSelectedChars([...selectedChars,card.id]);
    } else {
      if(actionCount>=30) return;
      if((acm[card.id]||0)>=2) return;
      // Legend: max 1 per deck
      if(isLegendCard(card)&&legendCount>=1&&!(acm[card.id]>0)) return showLimit('秘伝カードはデッキに1枚まで');
      // 元素変幻: max 1 per deck
      if(isGensoHenkan(card)&&ghCount>=1&&!(acm[card.id]>0)) return showLimit('元素変幻カードはデッキに1枚まで');
      setSelectedActions([...selectedActions,card.id]);
    }
  },[charCount,actionCount,selectedChars,selectedActions,acm,legendCount,ghCount,setSelectedChars,setSelectedActions]);

  const removeCard=useCallback((card)=>{
    if(card.type==='character'){
      setSelectedChars(selectedChars.filter((id,i,a)=>!(id===card.id&&i===a.lastIndexOf(card.id))));
    } else {
      const idx=selectedActions.lastIndexOf(card.id);
      if(idx>=0) setSelectedActions(selectedActions.filter((_,i)=>i!==idx));
    }
  },[selectedChars,selectedActions,setSelectedChars,setSelectedActions]);

  const deckActionCards=useMemo(()=>{
    const seen=new Set();
    return selectedActions.filter(id=>{ if(seen.has(id)) return false; seen.add(id); return true; })
      .map(id=>cards[id]).filter(Boolean);
  },[selectedActions,cards]);

  const handleAutoGen=()=>{
    const{chars,actions}=autoGenerateDeck(cards,cardTags,tags,tagCombos);
    setSelectedChars(chars); setSelectedActions(actions);
    setAutoMsg('デッキを自動生成しました！'); setTimeout(()=>setAutoMsg(''),3000);
  };

  const activeCombos=useMemo(()=>getActiveComboDetails(selectedChars,selectedActions,cardTags,tags,tagCombos),
    [selectedChars,selectedActions,cardTags,tags,tagCombos]);

  const scoreColor=score>10?'#34d399':score<-10?'#f87171':score>0?'#fbbf24':'#94a3b8';

  const PoolPanel=(
    <div className="card-pool glass-panel">
      <div className="pool-header">
        <input className="search-input" placeholder="カード名で検索..."
          value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/>
        <span className="pool-count">{filtered.length}枚</span>
      </div>
      <div className="filters">
        {TF.map(t=>(
          <button key={t} className={`filter-btn ${typeFilter===t?'active':''}`}
            onClick={()=>{setTF(t);setPage(0);}}>
            {t==='all'?'全て':TL[t]}
          </button>
        ))}
      </div>
      <div className="filters">
        {EF.map(el=>(
          <button key={el} className={`filter-btn ${elemFilter===el?'active':''}`}
            style={elemFilter===el&&el!=='all'?{background:(EC[el]||'#94a3b8')+'33',borderColor:EC[el]||'#94a3b8',color:EC[el]||'#94a3b8'}:{}}
            onClick={()=>{setEF(el);setPage(0);}}>
            {el==='all'?'全元素':el}
          </button>
        ))}
      </div>
      <div className="cards-grid">
        {pageCards.map(card=>{
          const cnt=card.type==='character'?(selectedChars.includes(card.id)?1:0):(acm[card.id]||0);
          const isLimited=(isLegendCard(card)&&legendCount>=1&&cnt===0)||(isGensoHenkan(card)&&ghCount>=1&&cnt===0);
          const isMaxed=card.type==='character'?(charCount>=3&&!selectedChars.includes(card.id)):(actionCount>=30||cnt>=2);
          return(<TcgCard key={card.id} card={card} count={cnt} isMaxed={isMaxed} isLimited={isLimited}
            onAdd={addCard} onRemove={removeCard}
            onHover={setHovered} onLeave={()=>setHovered(null)} onMouseMove={handleMM}
            onTouchStart={handleTouchStart}/>);
        })}
      </div>
      <div className="pagination">
        <button className="page-btn" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={15}/></button>
        <span className="page-info">{page+1}/{Math.max(1,totalPages)}</span>
        <button className="page-btn" disabled={page>=totalPages-1} onClick={()=>setPage(p=>p+1)}><ChevronRight size={15}/></button>
      </div>
    </div>
  );

  const DeckPanel=(
    <div className="deck-area glass-panel">
      <div className="deck-score-box" style={{borderColor:scoreColor+'44'}}>
        <span className="score-label">デッキスコア</span>
        <span className="score-value" style={{color:scoreColor}}>{score>0?'+':''}{score}</span>
        <span className="score-sub">{charCount}/3 キャラ ・ {actionCount}/30 アクション</span>
      </div>

      {activeCombos.length>0&&(
        <div className="active-combos">
          <div className="active-combos-title"><Zap size={12}/> 発動中コンボ</div>
          {activeCombos.map(c=>(
            <div key={c.id} className="active-combo-item">
              <span className="tag-pill" style={{fontSize:'.68rem'}}>{c.triggerTag}</span>
              <span style={{color:'#475569',fontSize:'.72rem'}}>×</span>
              <span className="tag-pill" style={{fontSize:'.68rem'}}>{c.conditionTag}</span>
              <span style={{color:'#475569',fontSize:'.72rem'}}>→</span>
              <span className="tag-pill" style={{fontSize:'.68rem'}}>{c.targetTag}</span>
              <span style={{color:c.overrideScore>0?'#34d399':'#f87171',fontWeight:700,fontSize:'.8rem'}}>
                {c.overrideScore>0?`+${c.overrideScore}`:c.overrideScore}
              </span>
            </div>
          ))}
        </div>
      )}

      {limitMsg&&<div className="limit-msg">{limitMsg}</div>}

      <div className="deck-action-btns">
        <button className="deck-btn auto-btn" onClick={handleAutoGen}><Wand2 size={13}/> 自動生成</button>
        <button className="deck-btn clear-btn" onClick={()=>{setSelectedChars([]);setSelectedActions([]);}}><Trash2 size={13}/> クリア</button>
        <button className="deck-btn" onClick={()=>setShowPreset(true)}><FolderOpen size={13}/> プリセット</button>
      </div>

      {autoMsg&&<div className="auto-gen-msg">{autoMsg}</div>}

      <div className="deck-section">
        <div className="deck-section-title"><span>キャラクター</span><span>{charCount}/3</span></div>
        <div className="deck-slots chars">
          {[0,1,2].map(i=>(
            <CharSlot key={i} card={cards[selectedChars[i]]}
              onHover={setHovered} onLeave={()=>setHovered(null)} onMouseMove={handleMM}
              onTouchStart={handleTouchStart}
              onRemove={removeCard}/>
          ))}
        </div>
      </div>

      <div className="deck-section deck-actions-section">
        <div className="deck-section-title"><span>アクション</span><span>{actionCount}/30</span></div>
        <div className="deck-action-list">
          {deckActionCards.length===0&&<p className="deck-empty">カードをクリックして追加</p>}
          {deckActionCards.map(card=>(
            <ActionRow key={card.id} card={card} count={acm[card.id]}
              onAdd={addCard} onRemove={removeCard}
              onHover={setHovered} onLeave={()=>setHovered(null)} onMouseMove={handleMM}
              onTouchStart={handleTouchStart}
              cardTags={cardTags} tags={tags} tagCombos={tagCombos}/>
          ))}
        </div>
      </div>
    </div>
  );

  return(
    <div className="deck-builder-layout" 
      onMouseMove={handleMM} 
      onTouchMove={handleTouchMove} 
      onTouchEnd={handleTouchEnd}
      onTouchCancel={handleTouchEnd}>
      <div className="deck-builder-desktop">{PoolPanel}{DeckPanel}</div>
      <div className="deck-builder-mobile">
        <div className="mobile-tab-bar">
          <button className={`mobile-tab ${mobilePanel==='pool'?'active':''}`} onClick={()=>setMobilePanel('pool')}>
            <List size={15}/> カード一覧
          </button>
          <button className={`mobile-tab ${mobilePanel==='deck'?'active':''}`} onClick={()=>setMobilePanel('deck')}>
            <Layers size={15}/> デッキ ({charCount+actionCount})
          </button>
        </div>
        {mobilePanel==='pool'?PoolPanel:DeckPanel}
      </div>

      {showPreset&&(
        <PresetModal onClose={()=>setShowPreset(false)}
          selectedChars={selectedChars} selectedActions={selectedActions} score={score}
          onLoad={p=>{setSelectedChars(p.chars||[]);setSelectedActions(p.actions||[]);}}/>
      )}

      <CardTooltip card={hovered} mousePos={mousePos} cardTags={cardTags} tags={tags} tagCombos={tagCombos}/>
    </div>
  );
}
