import React, { useState, useEffect, useRef, useCallback } from 'react';
import { autoGenerateDeck } from '../utils/scoring';
import { Wand2, Save, FolderOpen, Trash2, ChevronLeft, ChevronRight, Plus, Minus, Zap } from 'lucide-react';

// ── Cost display helpers ─────────────────────────────────────────────────────
const COST_TYPE_JP = {
  GCG_COST_DICE_CRYO:    '氷',
  GCG_COST_DICE_HYDRO:   '水',
  GCG_COST_DICE_PYRO:    '炎',
  GCG_COST_DICE_ELECTRO: '雷',
  GCG_COST_DICE_ANEMO:   '風',
  GCG_COST_DICE_GEO:     '岩',
  GCG_COST_DICE_DENDRO:  '草',
  GCG_COST_DICE_SAME:    '同一',
  GCG_COST_DICE_VOID:    '無色',
};

const ELEMENT_COLORS = {
  氷: '#93c5fd', 水: '#60a5fa', 炎: '#f87171', 雷: '#c084fc',
  風: '#34d399', 岩: '#fbbf24', 草: '#4ade80', 無色: '#94a3b8',
};

const TYPE_LABELS = {
  character: 'キャラ', weapon: '武器', artifact: '聖遺物',
  talent: '天賦', support: 'サポート', event: 'イベント',
};

const TYPE_COLORS = {
  character: '#f87171', weapon: '#60a5fa', artifact: '#c084fc',
  talent: '#fbbf24', support: '#34d399', event: '#94a3b8',
};

function formatCost(cost) {
  if (cost === null || cost === undefined) return 'コストなし';
  if (typeof cost === 'number') return `${cost} エナジー`;
  if (Array.isArray(cost)) {
    const parts = cost
      .filter(c => c.cost_type !== 'GCG_COST_INVALID' && c.count)
      .map(c => `${COST_TYPE_JP[c.cost_type] || c.cost_type}×${c.count}`);
    return parts.length ? parts.join(' + ') : 'コストなし';
  }
  return 'コストなし';
}

// ── Tooltip ──────────────────────────────────────────────────────────────────
function CardTooltip({ card, mousePos, ratings }) {
  if (!card) return null;
  const rating = ratings[card.id] || 0;
  const elemColor = ELEMENT_COLORS[card.element] || '#94a3b8';

  const tooltipWidth = 280;
  const tooltipHeight = 320;
  let left = mousePos.x + 16;
  let top = mousePos.y - 60;
  if (left + tooltipWidth > window.innerWidth - 8) left = mousePos.x - tooltipWidth - 8;
  if (top + tooltipHeight > window.innerHeight - 8) top = window.innerHeight - tooltipHeight - 8;
  if (top < 8) top = 8;

  return (
    <div className="card-tooltip" style={{ left, top }}>
      <div className="tooltip-header" style={{ borderColor: elemColor }}>
        <img src={card.url} alt={card.name} className="tooltip-img"
             onError={e => { e.target.style.display = 'none'; }} />
        <div className="tooltip-title">
          <span className="tooltip-name">{card.name}</span>
          <div className="tooltip-badges">
            <span className="tooltip-badge" style={{ background: TYPE_COLORS[card.type] + '33', color: TYPE_COLORS[card.type], border: `1px solid ${TYPE_COLORS[card.type]}66` }}>
              {TYPE_LABELS[card.type] || card.type}
            </span>
            <span className="tooltip-badge" style={{ background: elemColor + '22', color: elemColor, border: `1px solid ${elemColor}55` }}>
              {card.element}
            </span>
          </div>
        </div>
      </div>

      <div className="tooltip-stats">
        {card.type === 'character' && (
          <div className="tooltip-stat-row">
            <span className="tooltip-stat-label">HP</span>
            <span className="tooltip-stat-value" style={{ color: '#f87171' }}>♥ {card.hp}</span>
          </div>
        )}
        <div className="tooltip-stat-row">
          <span className="tooltip-stat-label">{card.type === 'character' ? 'エナジー' : 'コスト'}</span>
          <span className="tooltip-stat-value">{formatCost(card.cost)}</span>
        </div>
        {card.tags?.length > 0 && (
          <div className="tooltip-stat-row">
            <span className="tooltip-stat-label">タグ</span>
            <span className="tooltip-stat-value tooltip-tags">{card.tags.join(' / ')}</span>
          </div>
        )}
        {rating !== 0 && (
          <div className="tooltip-stat-row">
            <span className="tooltip-stat-label">評価</span>
            <span className="tooltip-stat-value" style={{ color: rating > 0 ? '#34d399' : '#f87171', fontWeight: 700 }}>
              {rating > 0 ? `+${rating}` : rating}
            </span>
          </div>
        )}
      </div>
      {card.desc && (
        <p className="tooltip-desc">{card.desc.replace(/\\n/g, ' ')}</p>
      )}
      <div className="tooltip-hint">
        <span>左クリック: デッキに追加</span>
        <span>右クリック: デッキから外す</span>
      </div>
    </div>
  );
}

// ── Individual card cell ──────────────────────────────────────────────────────
function TcgCard({ card, count, onAdd, onRemove, onHover, onLeave, onMouseMove, isMaxed }) {
  const elemColor = ELEMENT_COLORS[card.element] || '#94a3b8';
  const glowStyle = count > 0
    ? { borderColor: '#4f46e5', boxShadow: '0 0 12px rgba(79,70,229,0.5)' }
    : isMaxed
    ? { borderColor: '#f8717155', opacity: 0.5 }
    : {};

  const handleCtxMenu = useCallback((e) => {
    e.preventDefault();
    onRemove(card);
  }, [card, onRemove]);

  return (
    <div
      className={`tcg-card ${count > 0 ? 'selected' : ''}`}
      style={glowStyle}
      onClick={() => onAdd(card)}
      onContextMenu={handleCtxMenu}
      onMouseEnter={() => onHover(card)}
      onMouseLeave={onLeave}
      onMouseMove={onMouseMove}
    >
      <div className="card-elem-strip" style={{ background: elemColor }} />
      <img
        src={card.url}
        alt={card.name}
        className="card-img"
        loading="lazy"
        onError={e => { e.target.src = ''; e.target.style.background = '#334155'; }}
      />
      <span className="card-name">{card.name}</span>
      {count > 0 && <span className="card-badge">×{count}</span>}
    </div>
  );
}

// ── Deck Character Slot ───────────────────────────────────────────────────────
function CharSlot({ card, onHover, onLeave, onMouseMove, onRemove }) {
  if (!card) {
    return (
      <div className="deck-slot empty">
        <span>＋</span>
        <small>キャラ</small>
      </div>
    );
  }
  const elemColor = ELEMENT_COLORS[card.element] || '#94a3b8';

  return (
    <div
      className="deck-slot filled"
      style={{ borderColor: elemColor + '99', boxShadow: `0 0 10px ${elemColor}33` }}
      onMouseEnter={() => onHover(card)}
      onMouseLeave={onLeave}
      onMouseMove={onMouseMove}
      onClick={() => onRemove(card)}
      onContextMenu={e => { e.preventDefault(); onRemove(card); }}
      title="クリックで外す"
    >
      <img src={card.url} alt={card.name} onError={e => { e.target.style.display='none'; }} />
      <div className="slot-overlay">
        <span className="slot-name">{card.name}</span>
        <span className="slot-elem" style={{ color: elemColor }}>{card.element}</span>
        <span className="slot-hp">♥ {card.hp}</span>
      </div>
    </div>
  );
}

// ── Deck Action Row ───────────────────────────────────────────────────────────
function ActionRow({ card, count, onAdd, onRemove, onHover, onLeave, onMouseMove, rating }) {
  return (
    <div
      className="action-row"
      onMouseEnter={() => onHover(card)}
      onMouseLeave={onLeave}
      onMouseMove={onMouseMove}
    >
      <img src={card.url} alt={card.name} className="action-thumb"
           onError={e => { e.target.style.visibility='hidden'; }} />
      <span className="action-name">{card.name}</span>
      {rating !== 0 && (
        <span className="action-rating" style={{ color: rating > 0 ? '#34d399' : '#f87171' }}>
          {rating > 0 ? `+${rating}` : rating}
        </span>
      )}
      <div className="action-controls">
        <button className="btn-icon" onClick={() => onRemove(card)} title="1枚減らす">
          <Minus size={14} />
        </button>
        <span className="action-count">×{count}</span>
        <button className="btn-icon" onClick={() => onAdd(card)} title="1枚増やす" disabled={count >= 2}>
          <Plus size={14} />
        </button>
      </div>
    </div>
  );
}

// ── Preset Manager ────────────────────────────────────────────────────────────
function PresetManager({ selectedChars, selectedActions, onLoad, score }) {
  const [presets, setPresets] = useState(() => {
    try { return JSON.parse(localStorage.getItem('gcg_presets') || '[]'); } catch { return []; }
  });
  const [name, setName] = useState('');
  const [open, setOpen] = useState(false);

  const savePreset = () => {
    if (!name.trim()) return;
    const preset = {
      id: Date.now().toString(),
      name: name.trim(),
      chars: [...selectedChars],
      actions: [...selectedActions],
      score,
      date: new Date().toLocaleDateString('ja-JP'),
    };
    const updated = [preset, ...presets].slice(0, 20);
    setPresets(updated);
    localStorage.setItem('gcg_presets', JSON.stringify(updated));
    setName('');
  };

  const deletePreset = (id) => {
    const updated = presets.filter(p => p.id !== id);
    setPresets(updated);
    localStorage.setItem('gcg_presets', JSON.stringify(updated));
  };

  return (
    <div className="preset-manager">
      <button className="preset-toggle-btn" onClick={() => setOpen(o => !o)}>
        <FolderOpen size={16} />
        プリセット {presets.length > 0 && <span className="preset-count">{presets.length}</span>}
      </button>

      {open && (
        <div className="preset-panel glass-panel">
          <div className="preset-save-row">
            <input
              className="preset-name-input"
              placeholder="デッキ名を入力..."
              value={name}
              onChange={e => setName(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && savePreset()}
            />
            <button className="import-btn" onClick={savePreset} disabled={!name.trim()}>
              <Save size={14} /> 保存
            </button>
          </div>
          <div className="preset-list">
            {presets.length === 0 && <p className="preset-empty">保存されたデッキはありません</p>}
            {presets.map(p => (
              <div key={p.id} className="preset-item">
                <div className="preset-info">
                  <span className="preset-name">{p.name}</span>
                  <span className="preset-meta">スコア {p.score > 0 ? '+' : ''}{p.score} • {p.date}</span>
                </div>
                <div className="preset-actions">
                  <button className="btn-icon" onClick={() => onLoad(p)} title="読み込む">
                    <FolderOpen size={14} />
                  </button>
                  <button className="btn-icon danger" onClick={() => deletePreset(p.id)} title="削除">
                    <Trash2 size={14} />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ── Main DeckBuilder ──────────────────────────────────────────────────────────
const PAGE_SIZE = 48;
const TYPE_FILTERS = ['all', 'character', 'weapon', 'artifact', 'talent', 'support', 'event'];
const ELEMENT_FILTERS = ['all', '氷', '水', '炎', '雷', '風', '岩', '草', '無色'];

export default function DeckBuilder({
  cards, selectedChars, setSelectedChars,
  selectedActions, setSelectedActions, score, ratings,
}) {
  const [typeFilter, setTypeFilter] = useState('all');
  const [elemFilter, setElemFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(0);
  const [hovered, setHovered] = useState(null);
  const [mousePos, setMousePos] = useState({ x: 0, y: 0 });
  const [autoGenMsg, setAutoGenMsg] = useState('');

  const handleMouseMove = useCallback((e) => {
    setMousePos({ x: e.clientX, y: e.clientY });
  }, []);

  // ── Filtering ────────────────────────────────────────────────────────────
  const filtered = React.useMemo(() => {
    return Object.values(cards).filter(c => {
      if (typeFilter !== 'all' && c.type !== typeFilter) return false;
      if (elemFilter !== 'all' && c.element !== elemFilter) return false;
      if (search && !c.name.toLowerCase().includes(search.toLowerCase())) return false;
      return true;
    });
  }, [cards, typeFilter, elemFilter, search]);

  const totalPages = Math.ceil(filtered.length / PAGE_SIZE);
  const pageCards = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);

  const resetPage = () => setPage(0);

  // ── Count helpers ─────────────────────────────────────────────────────────
  const actionCountMap = React.useMemo(() => {
    const m = {};
    selectedActions.forEach(id => { m[id] = (m[id] || 0) + 1; });
    return m;
  }, [selectedActions]);

  const getCardCount = (card) => {
    if (card.type === 'character') return selectedChars.includes(card.id) ? 1 : 0;
    return actionCountMap[card.id] || 0;
  };

  const charCount = selectedChars.length;
  const actionCount = selectedActions.length;

  // ── Add / Remove ──────────────────────────────────────────────────────────
  const addCard = useCallback((card) => {
    if (card.type === 'character') {
      if (charCount >= 3 || selectedChars.includes(card.id)) return;
      setSelectedChars([...selectedChars, card.id]);
    } else {
      if (actionCount >= 30) return;
      if ((actionCountMap[card.id] || 0) >= 2) return;
      setSelectedActions([...selectedActions, card.id]);
    }
  }, [charCount, actionCount, selectedChars, selectedActions, actionCountMap, setSelectedChars, setSelectedActions]);

  const removeCard = useCallback((card) => {
    if (card.type === 'character') {
      const idx = selectedChars.indexOf(card.id);
      if (idx >= 0) setSelectedChars(selectedChars.filter((_, i) => i !== idx));
    } else {
      const idx = selectedActions.lastIndexOf(card.id);
      if (idx >= 0) setSelectedActions(selectedActions.filter((_, i) => i !== idx));
    }
  }, [selectedChars, selectedActions, setSelectedChars, setSelectedActions]);

  // ── Deck action cards (unique, sorted) ────────────────────────────────────
  const deckActionCards = React.useMemo(() => {
    const seen = new Set();
    const result = [];
    selectedActions.forEach(id => {
      if (!seen.has(id)) {
        seen.add(id);
        if (cards[id]) result.push(cards[id]);
      }
    });
    return result;
  }, [selectedActions, cards]);

  // ── Auto-generate ─────────────────────────────────────────────────────────
  const handleAutoGenerate = () => {
    const { chars, actions } = autoGenerateDeck(cards, ratings);
    setSelectedChars(chars);
    setSelectedActions(actions);
    setAutoGenMsg(`デッキを生成しました！(${chars.length}キャラ + ${actions.length}アクション)`);
    setTimeout(() => setAutoGenMsg(''), 3000);
  };

  // ── Load preset ───────────────────────────────────────────────────────────
  const handleLoadPreset = (preset) => {
    setSelectedChars(preset.chars || []);
    setSelectedActions(preset.actions || []);
  };

  // ── Clear deck ────────────────────────────────────────────────────────────
  const clearDeck = () => {
    setSelectedChars([]);
    setSelectedActions([]);
  };

  // ── Colour for score ──────────────────────────────────────────────────────
  const scoreColor = score > 10 ? '#34d399' : score < -10 ? '#f87171' : score > 0 ? '#fbbf24' : '#94a3b8';

  return (
    <div className="deck-builder-layout" onMouseMove={handleMouseMove}>
      {/* ─── Left: Card Pool ─────────────────────────────── */}
      <div className="card-pool glass-panel">
        <div className="pool-header">
          <input
            className="search-input"
            placeholder="カード名で検索..."
            value={search}
            onChange={e => { setSearch(e.target.value); resetPage(); }}
          />
          <span className="pool-count">{filtered.length}枚</span>
        </div>

        {/* Type filters */}
        <div className="filters">
          {TYPE_FILTERS.map(t => (
            <button key={t}
              className={`filter-btn ${typeFilter === t ? 'active' : ''}`}
              onClick={() => { setTypeFilter(t); resetPage(); }}
            >
              {t === 'all' ? '全て' : TYPE_LABELS[t]}
            </button>
          ))}
        </div>

        {/* Element filters */}
        <div className="filters elem-filters">
          {ELEMENT_FILTERS.map(el => (
            <button key={el}
              className={`filter-btn elem-btn ${elemFilter === el ? 'active' : ''}`}
              style={elemFilter === el && el !== 'all' ? {
                background: (ELEMENT_COLORS[el] || '#94a3b8') + '33',
                borderColor: ELEMENT_COLORS[el] || '#94a3b8',
                color: ELEMENT_COLORS[el] || '#94a3b8',
              } : {}}
              onClick={() => { setElemFilter(el); resetPage(); }}
            >
              {el === 'all' ? '全元素' : el}
            </button>
          ))}
        </div>

        {/* Card grid */}
        <div className="cards-grid">
          {pageCards.map(card => {
            const count = getCardCount(card);
            const isMaxed = card.type === 'character'
              ? (charCount >= 3 && !selectedChars.includes(card.id))
              : (actionCount >= 30 || (count >= 2));
            return (
              <TcgCard
                key={card.id}
                card={card}
                count={count}
                onAdd={addCard}
                onRemove={removeCard}
                onHover={setHovered}
                onLeave={() => setHovered(null)}
                onMouseMove={handleMouseMove}
                isMaxed={isMaxed}
              />
            );
          })}
        </div>

        {/* Pagination */}
        <div className="pagination">
          <button className="page-btn" disabled={page === 0} onClick={() => setPage(p => p - 1)}>
            <ChevronLeft size={16} />
          </button>
          <span className="page-info">{page + 1} / {Math.max(1, totalPages)}</span>
          <button className="page-btn" disabled={page >= totalPages - 1} onClick={() => setPage(p => p + 1)}>
            <ChevronRight size={16} />
          </button>
        </div>
      </div>

      {/* ─── Right: Deck Area ────────────────────────────── */}
      <div className="deck-area glass-panel">
        {/* Score */}
        <div className="deck-score-box" style={{ borderColor: scoreColor + '44', boxShadow: `0 0 20px ${scoreColor}11` }}>
          <span className="score-label">デッキスコア</span>
          <span className="score-value" style={{ color: scoreColor }}>
            {score > 0 ? '+' : ''}{score}
          </span>
          <span className="score-sub">{charCount}/3 キャラ ・ {actionCount}/30 アクション</span>
        </div>

        {/* Action buttons row */}
        <div className="deck-action-btns">
          <button className="deck-btn auto-btn" onClick={handleAutoGenerate}>
            <Wand2 size={15} /> 自動生成
          </button>
          <button className="deck-btn clear-btn" onClick={clearDeck}>
            <Trash2 size={15} /> クリア
          </button>
          <PresetManager
            selectedChars={selectedChars}
            selectedActions={selectedActions}
            onLoad={handleLoadPreset}
            score={score}
          />
        </div>

        {autoGenMsg && <div className="auto-gen-msg">{autoGenMsg}</div>}

        {/* Character slots */}
        <div className="deck-section">
          <div className="deck-section-title">
            <span>キャラクター</span>
            <span>{charCount}/3</span>
          </div>
          <div className="deck-slots chars">
            {[0, 1, 2].map(i => (
              <CharSlot
                key={i}
                card={cards[selectedChars[i]]}
                onHover={setHovered}
                onLeave={() => setHovered(null)}
                onMouseMove={handleMouseMove}
                onRemove={removeCard}
              />
            ))}
          </div>
        </div>

        {/* Action cards */}
        <div className="deck-section deck-actions-section">
          <div className="deck-section-title">
            <span>アクションカード</span>
            <span>{actionCount}/30</span>
          </div>
          <div className="deck-action-list">
            {deckActionCards.length === 0 && (
              <p className="deck-empty">カードをクリックしてデッキに追加</p>
            )}
            {deckActionCards.map(card => (
              <ActionRow
                key={card.id}
                card={card}
                count={actionCountMap[card.id]}
                onAdd={addCard}
                onRemove={removeCard}
                onHover={setHovered}
                onLeave={() => setHovered(null)}
                onMouseMove={handleMouseMove}
                rating={ratings[card.id] || 0}
              />
            ))}
          </div>
        </div>
      </div>

      {/* ─── Floating Tooltip ────────────────────────────── */}
      <CardTooltip card={hovered} mousePos={mousePos} ratings={ratings} />
    </div>
  );
}