import React,{useState,useCallback,useMemo,useRef,useEffect} from 'react';
import {Wand2,Save,FolderOpen,Trash2,ChevronLeft,ChevronRight,Plus,Minus,Layers,List,X,Zap,Eye} from 'lucide-react';
import {autoGenerateDeck,calcCardScore,getActiveComboDetails,isLegendCard,isGensoHenkan,adjTagKey,isAdjTag} from '../utils/tagScoring';
import {loadPresets,savePresets} from '../utils/storage';
import FilterSortBar,{applyFilterSort} from './FilterSortBar';

// ── Constants ─────────────────────────────────────────────────────────────────
const COST_JP={GCG_COST_DICE_CRYO:'氷',GCG_COST_DICE_HYDRO:'水',GCG_COST_DICE_PYRO:'炎',
  GCG_COST_DICE_ELECTRO:'雷',GCG_COST_DICE_ANEMO:'風',GCG_COST_DICE_GEO:'岩',
  GCG_COST_DICE_DENDRO:'草',GCG_COST_DICE_SAME:'同一',GCG_COST_DICE_VOID:'無色',GCG_COST_LEGEND:'秘伝'};
const EC={氷:'#93c5fd',水:'#60a5fa',炎:'#f87171',雷:'#c084fc',風:'#34d399',岩:'#fbbf24',草:'#4ade80',無色:'#94a3b8'};
const TL={character:'キャラ',weapon:'武器',artifact:'聖遺物',talent:'天賦',support:'サポート',event:'イベント'};
const TC={character:'#f87171',weapon:'#60a5fa',artifact:'#c084fc',talent:'#fbbf24',support:'#34d399',event:'#94a3b8'};
const TF=['all','character','weapon','artifact','talent','support','event'];
const EF=['all','氷','水','炎','雷','風','岩','草','無色'];

function fmtCost(cost){
  if(!cost) return 'なし';
  if(typeof cost==='number') return `${cost}`;
  if(Array.isArray(cost)){
    const p=cost.filter(c=>c.cost_type!=='GCG_COST_INVALID'&&c.count).map(c=>`${COST_JP[c.cost_type]||c.cost_type}×${c.count}`);
    return p.join('+')||'なし';
  }
  return 'なし';
}

// ── Long press hook ───────────────────────────────────────────────────────────
function useLongPress(onLong,onShort,delay=150){
  const timer=useRef(null);
  const fired=useRef(false);
  const start=useCallback((e)=>{
    fired.current=false;
    const ev=e.touches?.[0]??e;
    timer.current=setTimeout(()=>{ fired.current=true; onLong(ev); },delay);
  },[onLong,delay]);
  const end=useCallback((e)=>{
    clearTimeout(timer.current);
    if(!fired.current) onShort(e);
    fired.current=false;
  },[onShort]);
  const cancel=useCallback(()=>{ clearTimeout(timer.current); fired.current=false; },[]);
  return{
    onMouseDown:start,onMouseUp:end,onMouseLeave:cancel,
    onTouchStart:(e)=>{e.preventDefault();start(e);},
    onTouchEnd:(e)=>{e.preventDefault();end(e);},
    onTouchMove:cancel,
  };
}

// ── Image preview overlay ─────────────────────────────────────────────────────
function ImgPreview({card,onClose}){
  if(!card) return null;
  const ec=EC[card.element]||'#94a3b8';
  return(
    <div className="img-preview-overlay" onClick={onClose}>
      <div className="img-preview-box" onClick={e=>e.stopPropagation()} style={{borderColor:ec}}>
        <img src={card.url} alt={card.name} onError={e=>e.target.style.display='none'}/>
        <div className="img-preview-info">
          <span style={{fontWeight:700,fontSize:'1rem'}}>{card.name}</span>
          <span style={{color:TC[card.type],fontSize:'.8rem'}}>{TL[card.type]}</span>
          <span style={{color:ec,fontSize:'.8rem'}}>{card.element}</span>
          {card.type==='character'&&<span style={{color:'#fca5a5',fontSize:'.8rem'}}>HP {card.hp}</span>}
          <span style={{color:'#94a3b8',fontSize:'.78rem'}}>コスト: {fmtCost(card.cost)}</span>
        </div>
        <button className="btn-icon" style={{position:'absolute',top:6,right:6}} onClick={onClose}><X size={16}/></button>
      </div>
    </div>
  );
}

// ── Desktop tooltip ───────────────────────────────────────────────────────────
function CardTooltip({card,mousePos,cardTags,tags,tagCombos,calcAdjusters}){
  if(!card) return null;
  const myTags=(cardTags[card.id]||[]).filter(t=>!isAdjTag(t));
  const s=calcCardScore(card.id,cardTags,tags,tagCombos,calcAdjusters);
  const ec=EC[card.element]||'#94a3b8';
  let left=mousePos.x+16,top=mousePos.y-50;
  if(left+260>window.innerWidth-8) left=mousePos.x-268;
  if(top+280>window.innerHeight-8) top=window.innerHeight-288;
  if(top<8) top=8;
  return(
    <div className="card-tooltip" style={{left,top}}>
      <div className="tooltip-header" style={{borderBottomColor:ec+'55'}}>
        <img src={card.url} alt="" className="tooltip-img" onError={e=>e.target.style.display='none'}/>
        <div className="tooltip-title">
          <span className="tooltip-name">{card.name}</span>
          <div className="tooltip-badges">
            <span className="tooltip-badge" style={{color:TC[card.type],borderColor:TC[card.type]+'55'}}>{TL[card.type]}</span>
            <span className="tooltip-badge" style={{color:ec,borderColor:ec+'55'}}>{card.element}</span>
            {isLegendCard(card)&&<span className="tooltip-badge" style={{color:'#fbbf24',borderColor:'#fbbf2455'}}>秘伝</span>}
          </div>
        </div>
      </div>
      <div className="tooltip-stats">
        {card.type==='character'&&<div className="tooltip-stat-row"><span className="tooltip-stat-label">HP</span><span style={{color:'#f87171'}}>♥ {card.hp}</span></div>}
        <div className="tooltip-stat-row"><span className="tooltip-stat-label">コスト</span><span>{fmtCost(card.cost)}</span></div>
        {myTags.length>0&&<div className="tooltip-stat-row"><span className="tooltip-stat-label">タグ</span><span style={{fontSize:'.73rem'}}>{[...new Set(myTags)].map(t=>{const c=myTags.filter(x=>x===t).length;return c>1?`${t}×${c}`:t;}).join(' ')}</span></div>}
        {s!==0&&<div className="tooltip-stat-row"><span className="tooltip-stat-label">スコア</span><span style={{color:s>0?'#34d399':'#f87171',fontWeight:700}}>{s>0?`+${s}`:s}</span></div>}
      </div>
      {card.desc&&<p className="tooltip-desc">{card.desc.replace(/\\n/g,' ')}</p>}
      <div className="tooltip-hint"><span>左クリック: 追加</span><span>右クリック: 外す</span></div>
    </div>
  );
}

// ── Desktop card cell ─────────────────────────────────────────────────────────
function DesktopCard({card,count,onAdd,onRemove,onHover,onLeave,onMouseMove,isMaxed,isLimited}){
  const ec=EC[card.element]||'#94a3b8';
  return(
    <div className={`tcg-card ${count>0?'selected':''} ${isMaxed||isLimited?'maxed':''}`}
      onClick={()=>onAdd(card)}
      onContextMenu={e=>{e.preventDefault();onRemove(card);}}
      onMouseEnter={()=>onHover(card)} onMouseLeave={onLeave} onMouseMove={onMouseMove}>
      <div className="card-elem-strip" style={{background:ec}}/>
      <img src={card.url} alt={card.name} className="card-img" loading="lazy"
        onError={e=>{e.target.style.background='#1e293b';e.target.src='';}}/>
      <span className="card-name">{card.name}</span>
      {count>0&&<span className="card-badge">×{count}</span>}
      {isLegendCard(card)&&<span className="card-legend-badge">秘</span>}
    </div>
  );
}

// ── Mobile card cell (name-based, long press for image) ───────────────────────
function MobileCard({card,count,onAdd,onRemove,onPreview,isMaxed,isLimited}){
  const ec=EC[card.element]||'#94a3b8';
  const handlers=useLongPress(
    ()=>onPreview(card),   // long press → image preview
    ()=>onAdd(card),       // short tap  → add
  );
  const handleRemove=(e)=>{ e.preventDefault(); e.stopPropagation(); onRemove(card); };
  return(
    <div className={`mob-card ${count>0?'selected':''} ${isMaxed||isLimited?'maxed':''}`} {...handlers}
      onContextMenu={handleRemove}>
      <div className="mob-card-elem" style={{background:ec}}/>
      <span className="mob-card-name">{card.name}</span>
      <span className="mob-card-type" style={{color:TC[card.type]}}>{TL[card.type]}</span>
      {count>0&&<span className="mob-card-count">×{count}</span>}
      {count>0&&<button className="mob-minus-btn" onTouchStart={e=>{e.stopPropagation();}} onTouchEnd={e=>{e.preventDefault();e.stopPropagation();onRemove(card);}}>−</button>}
    </div>
  );
}

// ── CharSlot ──────────────────────────────────────────────────────────────────
function CharSlot({card,onHover,onLeave,onMouseMove,onRemove,onPreview,isMobile}){
  const handlers=isMobile?useLongPress(()=>onPreview&&onPreview(card),()=>onRemove(card)):null;
  if(!card) return(<div className="deck-slot empty"><span>＋</span><small>キャラ</small></div>);
  const ec=EC[card.element]||'#94a3b8';
  return(
    <div className="deck-slot filled" style={{borderColor:ec+'99'}}
      {...(isMobile?handlers:{
        onMouseEnter:()=>onHover(card),onMouseLeave:onLeave,onMouseMove:onMouseMove,
        onClick:()=>onRemove(card),onContextMenu:e=>{e.preventDefault();onRemove(card);}
      })}>
      <img src={card.url} alt={card.name} onError={e=>e.target.style.display='none'}/>
      <div className="slot-overlay">
        <span className="slot-name">{card.name}</span>
        <span className="slot-elem" style={{color:ec}}>{card.element}</span>
        <span className="slot-hp">♥ {card.hp}</span>
      </div>
    </div>
  );
}

// ── ActionRow ─────────────────────────────────────────────────────────────────
function ActionRow({card,count,onAdd,onRemove,onHover,onLeave,onMouseMove,onPreview,cardTags,tags,tagCombos,calcAdjusters,isMobile}){
  const s=calcCardScore(card.id,cardTags,tags,tagCombos,calcAdjusters);
  const handlers=isMobile?useLongPress(()=>onPreview&&onPreview(card),()=>onAdd(card)):null;
  return(
    <div className="action-row"
      {...(isMobile?{...handlers,onContextMenu:e=>{e.preventDefault();onRemove(card);}}: {onMouseEnter:()=>onHover(card),onMouseLeave:onLeave,onMouseMove:onMouseMove})}>
      {!isMobile&&<img src={card.url} alt="" className="action-thumb" onError={e=>e.target.style.visibility='hidden'}/>}
      {isMobile&&<div className="action-elem-dot" style={{background:EC[card.element]||'#94a3b8'}}/>}
      <span className="action-name">{card.name}</span>
      {s!==0&&<span className="action-rating" style={{color:s>0?'#34d399':'#f87171'}}>{s>0?`+${s}`:s}</span>}
      <div className="action-controls">
        <button className="btn-icon" onClick={e=>{e.stopPropagation();onRemove(card);}}><Minus size={13}/></button>
        <span className="action-count">×{count}</span>
        <button className="btn-icon" onClick={e=>{e.stopPropagation();onAdd(card);}} disabled={count>=2}><Plus size={13}/></button>
      </div>
    </div>
  );
}

// ── Preset modal ──────────────────────────────────────────────────────────────
function PresetModal({onClose,selectedChars,selectedActions,score,onLoad}){
  const [presets,setPresets]=useState(()=>loadPresets());
  const [name,setName]=useState('');
  const save=()=>{
    if(!name.trim()) return;
    const p={id:Date.now().toString(),name:name.trim(),chars:[...selectedChars],
      characters:[...selectedChars],actions:[...selectedActions],score,date:new Date().toLocaleDateString('ja-JP')};
    const u=[p,...presets].slice(0,30);
    setPresets(u);savePresets(u);setName('');
  };
  const del=id=>{ const u=presets.filter(p=>p.id!==id); setPresets(u); savePresets(u); };
  return(
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-box glass-panel" onClick={e=>e.stopPropagation()}>
        <div className="modal-header"><h3>プリセット</h3><button className="btn-icon" onClick={onClose}><X size={18}/></button></div>
        <div className="preset-save-row">
          <input className="preset-name-input" placeholder="デッキ名..." value={name}
            onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&save()}/>
          <button className="import-btn" onClick={save} disabled={!name.trim()}><Save size={13}/> 保存</button>
        </div>
        <div className="preset-list">
          {presets.length===0&&<p className="empty-msg">保存なし</p>}
          {presets.map(p=>(
            <div key={p.id} className="preset-item">
              <div className="preset-info">
                <span className="preset-name">{p.name}</span>
                <span className="preset-meta">スコア {p.score>0?'+':''}{p.score} · {p.date}</span>
              </div>
              <div className="preset-actions">
                <button className="btn-icon" onClick={()=>{onLoad(p);onClose();}} title="読み込む"><FolderOpen size={13}/></button>
                <button className="btn-icon danger" onClick={()=>del(p.id)}><Trash2 size={13}/></button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function countLegend(ids,cards){return ids.filter(id=>isLegendCard(cards[id])).length;}
function countGH(ids,cards){return ids.filter(id=>isGensoHenkan(cards[id])).length;}

function usePageSize(){
  const get=()=>window.innerWidth<480?18:window.innerWidth<768?28:48;
  const [ps,set]=useState(get);
  useEffect(()=>{const h=()=>set(get());window.addEventListener('resize',h);return()=>window.removeEventListener('resize',h);},[]);
  return ps;
}

function useIsMobile(){
  const [m,set]=useState(()=>window.innerWidth<=768);
  useEffect(()=>{const h=()=>set(window.innerWidth<=768);window.addEventListener('resize',h);return()=>window.removeEventListener('resize',h);},[]);
  return m;
}

// ── Main DeckBuilder ──────────────────────────────────────────────────────────
export default function DeckBuilder({
  cards,selectedChars,setSelectedChars,selectedActions,setSelectedActions,
  score,cardTags,tags,tagCombos,calcAdjusters=[],
}){
  const PAGE_SIZE=usePageSize();
  const isMobile=useIsMobile();
  const [typeFilter,setTF]=useState('all');
  const [elemFilter,setEF]=useState('all');
  const [search,setSearch]=useState('');
  const [page,setPage]=useState(0);
  const [hovered,setHovered]=useState(null);
  const [mousePos,setMP]=useState({x:0,y:0});
  const [showPreset,setShowPreset]=useState(false);
  const [autoMsg,setAutoMsg]=useState('');
  const [mobilePanel,setMobilePanel]=useState('pool');
  const [limitMsg,setLimitMsg]=useState('');
  const [preview,setPreview]=useState(null);
  // Filter/sort state
  const [filterTags,setFilterTags]=useState([]);
  const [sortKeys,setSortKeys]=useState([]);
  const [sortDir,setSortDir]=useState('desc');

  const handleMM=useCallback(e=>setMP({x:e.clientX,y:e.clientY}),[]);

  const base=useMemo(()=>Object.values(cards).filter(c=>{
    if(typeFilter!=='all'&&c.type!==typeFilter) return false;
    if(elemFilter!=='all'&&c.element!==elemFilter) return false;
    if(search&&!c.name.includes(search)) return false;
    return true;
  }),[cards,typeFilter,elemFilter,search]);

  const filtered=useMemo(()=>applyFilterSort(base,cardTags,filterTags,sortKeys,sortDir),
    [base,cardTags,filterTags,sortKeys,sortDir]);

  const totalPages=Math.ceil(filtered.length/PAGE_SIZE);
  const pageCards=filtered.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);

  const acm=useMemo(()=>{const m={};selectedActions.forEach(id=>{m[id]=(m[id]||0)+1;});return m;},[selectedActions]);
  const charCount=selectedChars.length;
  const actionCount=selectedActions.length;
  const allDeck=[...selectedChars,...selectedActions];
  const legendCount=useMemo(()=>countLegend(allDeck,cards),[allDeck,cards]);
  const ghCount=useMemo(()=>countGH(allDeck,cards),[allDeck,cards]);

  const showLimit=msg=>{setLimitMsg(msg);setTimeout(()=>setLimitMsg(''),2500);};

  const addCard=useCallback((card)=>{
    if(card.type==='character'){
      if(charCount>=3||selectedChars.includes(card.id)) return;
      setSelectedChars([...selectedChars,card.id]);
    } else {
      if(actionCount>=30||(acm[card.id]||0)>=2) return;
      if(isLegendCard(card)&&legendCount>=1&&!acm[card.id]) return showLimit('秘伝カードはデッキに1枚まで');
      if(isGensoHenkan(card)&&ghCount>=1&&!acm[card.id]) return showLimit('元素変幻カードはデッキに1枚まで');
      setSelectedActions([...selectedActions,card.id]);
    }
  },[charCount,actionCount,selectedChars,selectedActions,acm,legendCount,ghCount,setSelectedChars,setSelectedActions]);

  const removeCard=useCallback((card)=>{
    if(card.type==='character'){
      const i=selectedChars.lastIndexOf(card.id);
      if(i>=0) setSelectedChars(selectedChars.filter((_,j)=>j!==i));
    } else {
      const i=selectedActions.lastIndexOf(card.id);
      if(i>=0) setSelectedActions(selectedActions.filter((_,j)=>j!==i));
    }
  },[selectedChars,selectedActions,setSelectedChars,setSelectedActions]);

  const deckActionCards=useMemo(()=>{
    const seen=new Set();
    return selectedActions.filter(id=>{if(seen.has(id))return false;seen.add(id);return true;}).map(id=>cards[id]).filter(Boolean);
  },[selectedActions,cards]);

  const handleAutoGen=()=>{
    const{chars,actions}=autoGenerateDeck(cards,cardTags,tags,tagCombos,calcAdjusters);
    setSelectedChars(chars);setSelectedActions(actions);
    setAutoMsg('デッキを自動生成しました！');setTimeout(()=>setAutoMsg(''),3000);
  };

  const activeCombos=useMemo(()=>getActiveComboDetails(selectedChars,selectedActions,cardTags,tags,tagCombos),
    [selectedChars,selectedActions,cardTags,tags,tagCombos]);

  const deckAdjApplied=useMemo(()=>{
    const allTags=[...selectedChars,...selectedActions].flatMap(id=>(cardTags[id]||[]).filter(t=>isAdjTag(t)));
    return allTags.map(t=>calcAdjusters?.find(a=>a.id===t.slice(4))).filter(a=>a?.scope==='deck');
  },[selectedChars,selectedActions,cardTags,calcAdjusters]);

  const scoreColor=score>10?'#34d399':score<-10?'#f87171':score>0?'#fbbf24':'#94a3b8';

  const PoolPanel=(
    <div className="card-pool glass-panel">
      <div className="pool-header">
        <input className="search-input" placeholder="カード名で検索..." value={search}
          onChange={e=>{setSearch(e.target.value);setPage(0);}}/>
        <span className="pool-count">{filtered.length}枚</span>
      </div>
      <div className="filters">
        {TF.map(t=>(
          <button key={t} className={`filter-btn ${typeFilter===t?'active':''}`}
            onClick={()=>{setTF(t);setPage(0);}}>
            {t==='all'?'全て':TL[t]}
          </button>
        ))}
      </div>
      <div className="filters">
        {EF.map(el=>(
          <button key={el} className={`filter-btn ${elemFilter===el?'active':''}`}
            style={elemFilter===el&&el!=='all'?{background:(EC[el]||'#94a3b8')+'33',borderColor:EC[el]||'#94a3b8',color:EC[el]||'#94a3b8'}:{}}
            onClick={()=>{setEF(el);setPage(0);}}>
            {el==='all'?'全元素':el}
          </button>
        ))}
      </div>
      <FilterSortBar tags={tags} filterTags={filterTags} onFilterChange={v=>{setFilterTags(v);setPage(0);}}
        sortKeys={sortKeys} onSortChange={setSortKeys} sortDir={sortDir} onSortDirChange={setSortDir}/>
      {isMobile?(
        <div className="mob-cards-grid">
          {pageCards.map(card=>{
            const cnt=card.type==='character'?(selectedChars.includes(card.id)?1:0):(acm[card.id]||0);
            const isLimited=(isLegendCard(card)&&legendCount>=1&&cnt===0)||(isGensoHenkan(card)&&ghCount>=1&&cnt===0);
            const isMaxed=card.type==='character'?(charCount>=3&&!selectedChars.includes(card.id)):(actionCount>=30||cnt>=2);
            return(<MobileCard key={card.id} card={card} count={cnt} isMaxed={isMaxed} isLimited={isLimited}
              onAdd={addCard} onRemove={removeCard} onPreview={setPreview}/>);
          })}
        </div>
      ):(
        <div className="cards-grid">
          {pageCards.map(card=>{
            const cnt=card.type==='character'?(selectedChars.includes(card.id)?1:0):(acm[card.id]||0);
            const isLimited=(isLegendCard(card)&&legendCount>=1&&cnt===0)||(isGensoHenkan(card)&&ghCount>=1&&cnt===0);
            const isMaxed=card.type==='character'?(charCount>=3&&!selectedChars.includes(card.id)):(actionCount>=30||cnt>=2);
            return(<DesktopCard key={card.id} card={card} count={cnt} isMaxed={isMaxed} isLimited={isLimited}
              onAdd={addCard} onRemove={removeCard} onHover={setHovered} onLeave={()=>setHovered(null)} onMouseMove={handleMM}/>);
          })}
        </div>
      )}
      <div className="pagination">
        <button className="page-btn" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={15}/></button>
        <span className="page-info">{page+1}/{Math.max(1,totalPages)}</span>
        <button className="page-btn" disabled={page>=totalPages-1} onClick={()=>setPage(p=>p+1)}><ChevronRight size={15}/></button>
      </div>
    </div>
  );

  const DeckPanel=(
    <div className="deck-area glass-panel">
      <div className="deck-score-box" style={{borderColor:scoreColor+'44'}}>
        <span className="score-label">デッキスコア</span>
        <span className="score-value" style={{color:scoreColor}}>{score>0?'+':''}{score}</span>
        <span className="score-sub">{charCount}/3 キャラ ・ {actionCount}/30 アクション</span>
      </div>
      {activeCombos.length>0&&(
        <div className="active-combos">
          <div className="active-combos-title"><Zap size={12}/> 発動中コンボ</div>
          {activeCombos.map(c=>(
            <div key={c.id} className="active-combo-item">
              <span className="tag-pill" style={{fontSize:'.68rem'}}>{c.triggerTag}</span>
              <span style={{color:'#475569',fontSize:'.72rem'}}>×</span>
              <span className="tag-pill" style={{fontSize:'.68rem'}}>{c.conditionTag}</span>
              <span style={{color:'#475569',fontSize:'.72rem'}}>→</span>
              <span className="tag-pill" style={{fontSize:'.68rem'}}>{c.targetTag}</span>
              <span style={{color:c.overrideScore>0?'#34d399':'#f87171',fontWeight:700,fontSize:'.8rem'}}>{c.overrideScore>0?`+${c.overrideScore}`:c.overrideScore}</span>
            </div>
          ))}
        </div>
      )}
      {deckAdjApplied.length>0&&(
        <div className="active-combos" style={{borderColor:'rgba(96,165,250,.3)',background:'rgba(96,165,250,.05)'}}>
          <div className="active-combos-title" style={{color:'#60a5fa'}}><Eye size={12}/> 計算調整（デッキ）</div>
          {deckAdjApplied.map((a,i)=>(
            <div key={i} className="active-combo-item">
              <span className="adj-op-badge" style={{color:a.opType==='×'?'#60a5fa':'#c084fc',borderColor:a.opType==='×'?'rgba(96,165,250,.4)':'rgba(192,132,252,.4)'}}>
                {a.opType} {a.value}
              </span>
              <span style={{color:'#475569',fontSize:'.72rem'}}>適用中</span>
            </div>
          ))}
        </div>
      )}
      {limitMsg&&<div className="limit-msg">{limitMsg}</div>}
      <div className="deck-action-btns">
        <button className="deck-btn auto-btn" onClick={handleAutoGen}><Wand2 size={13}/> 自動生成</button>
        <button className="deck-btn clear-btn" onClick={()=>{setSelectedChars([]);setSelectedActions([]);}}><Trash2 size={13}/> クリア</button>
        <button className="deck-btn" onClick={()=>setShowPreset(true)}><FolderOpen size={13}/> プリセット</button>
      </div>
      {autoMsg&&<div className="auto-gen-msg">{autoMsg}</div>}
      <div className="deck-section">
        <div className="deck-section-title"><span>キャラクター</span><span>{charCount}/3</span></div>
        <div className="deck-slots chars">
          {[0,1,2].map(i=>(
            <CharSlot key={i} card={cards[selectedChars[i]]} isMobile={isMobile}
              onHover={setHovered} onLeave={()=>setHovered(null)} onMouseMove={handleMM}
              onRemove={removeCard} onPreview={setPreview}/>
          ))}
        </div>
      </div>
      <div className="deck-section deck-actions-section">
        <div className="deck-section-title"><span>アクション</span><span>{actionCount}/30</span></div>
        <div className="deck-action-list">
          {deckActionCards.length===0&&<p className="deck-empty">カードをクリックして追加</p>}
          {deckActionCards.map(card=>(
            <ActionRow key={card.id} card={card} count={acm[card.id]} isMobile={isMobile}
              onAdd={addCard} onRemove={removeCard}
              onHover={setHovered} onLeave={()=>setHovered(null)} onMouseMove={handleMM}
              onPreview={setPreview} cardTags={cardTags} tags={tags} tagCombos={tagCombos} calcAdjusters={calcAdjusters}/>
          ))}
        </div>
      </div>
    </div>
  );

  return(
    <div className="deck-builder-layout" onMouseMove={isMobile?undefined:handleMM}>
      <div className="deck-builder-desktop">{PoolPanel}{DeckPanel}</div>
      <div className="deck-builder-mobile">
        <div className="mobile-tab-bar">
          <button className={`mobile-tab ${mobilePanel==='pool'?'active':''}`} onClick={()=>setMobilePanel('pool')}>
            <List size={15}/> カード一覧
          </button>
          <button className={`mobile-tab ${mobilePanel==='deck'?'active':''}`} onClick={()=>setMobilePanel('deck')}>
            <Layers size={15}/> デッキ ({charCount+actionCount})
          </button>
        </div>
        {mobilePanel==='pool'?PoolPanel:DeckPanel}
      </div>
      {showPreset&&(
        <PresetModal onClose={()=>setShowPreset(false)}
          selectedChars={selectedChars} selectedActions={selectedActions} score={score}
          onLoad={p=>{setSelectedChars(p.chars||p.characters||[]);setSelectedActions(p.actions||[]);}}/>
      )}
      {!isMobile&&<CardTooltip card={hovered} mousePos={mousePos} cardTags={cardTags} tags={tags} tagCombos={tagCombos} calcAdjusters={calcAdjusters}/>}
      <ImgPreview card={preview} onClose={()=>setPreview(null)}/>
    </div>
  );
}
