// cardTags = { [cardId]: string[] }  duplicates allowed, may contain 'adj:{id}' entries
// tags      = [{ id, name, score, groupId }]
// tagCombos = [{ id, triggerTag, conditionTag, targetTag, overrideScore, scope }]
// calcAdjusters = [{ id, opType:'×'|'÷', value:number, scope:'deck'|'card' }]

// adj: tags are stored as 'adj:{adjId}' in cardTags.
// Card-scope adjusters apply to each card's subtotal.
// Deck-scope adjusters from ALL cards in deck apply to final deck total.

export const ADJ_PREFIX='adj:';
export const adjTagKey=id=>`${ADJ_PREFIX}${id}`;
export const isAdjTag=t=>t.startsWith(ADJ_PREFIX);
export const adjIdFromTag=t=>t.slice(ADJ_PREFIX.length);

function buildScoreMap(tags){
  const m={};
  for(const t of tags) m[t.name]=t.score;
  return m;
}

function applyCombos(eff,tagSet,combos){
  for(const c of combos){
    if(tagSet.has(c.triggerTag)&&tagSet.has(c.conditionTag))
      eff[c.targetTag]=c.overrideScore;
  }
}

// Apply ordered ×/÷ operations to a running total
function applyAdjList(score,adjs){
  let v=score;
  for(const a of adjs){
    const n=Number(a.value);
    if(a.opType==='×') v=v*n;
    else if(a.opType==='÷'&&n!==0) v=v/n;
  }
  return Math.round(v*100)/100;
}

// Resolve adj: tag strings to adjuster objects for a given scope
function resolveAdjs(adjTags,calcAdjusters,scope){
  return adjTags
    .map(t=>calcAdjusters?.find(a=>a.id===adjIdFromTag(t)))
    .filter(a=>a&&a.scope===scope);
}

// ── Card score ────────────────────────────────────────────────────────────────
export function calcCardScore(cardId,cardTags,tags,tagCombos=[],calcAdjusters=[]){
  const all=cardTags[cardId]||[];
  const regular=all.filter(t=>!isAdjTag(t));
  const adjTags=all.filter(isAdjTag);

  const tagSet=new Set(regular);
  const eff={...buildScoreMap(tags)};
  applyCombos(eff,tagSet,tagCombos.filter(c=>c.scope==='card'));
  const subtotal=regular.reduce((s,n)=>s+(eff[n]??0),0);

  // Apply card-scoped adjusters assigned to this card
  const cardAdjs=resolveAdjs(adjTags,calcAdjusters,'card');
  return cardAdjs.length?applyAdjList(subtotal,cardAdjs):subtotal;
}

// ── Deck score ────────────────────────────────────────────────────────────────
export function calcDeckScore(chars,actions,cardTags,tags,tagCombos=[],calcAdjusters=[]){
  const allIds=[...chars,...actions];
  const allTags=allIds.flatMap(id=>cardTags[id]||[]);
  const regular=allTags.filter(t=>!isAdjTag(t));
  const adjTags=allTags.filter(isAdjTag);

  const deckTagSet=new Set(regular);
  const eff={...buildScoreMap(tags)};
  applyCombos(eff,deckTagSet,tagCombos.filter(c=>c.scope==='deck'||!c.scope));
  const subtotal=regular.reduce((s,n)=>s+(eff[n]??0),0);

  // Apply deck-scoped adjusters from all cards (each instance counts)
  const deckAdjs=resolveAdjs(adjTags,calcAdjusters,'deck');
  return deckAdjs.length?applyAdjList(subtotal,deckAdjs):subtotal;
}

// ── Active deck combo details ─────────────────────────────────────────────────
export function getActiveComboDetails(chars,actions,cardTags,tags,tagCombos=[]){
  const regular=[...chars,...actions].flatMap(id=>(cardTags[id]||[]).filter(t=>!isAdjTag(t)));
  const deckTagSet=new Set(regular);
  const base=buildScoreMap(tags);
  return tagCombos
    .filter(c=>(c.scope==='deck'||!c.scope)&&deckTagSet.has(c.triggerTag)&&deckTagSet.has(c.conditionTag))
    .map(c=>({...c,baseScore:base[c.targetTag]??0}));
}

// ── Meta analytics ────────────────────────────────────────────────────────────
export function getMetaAnalytics(metaDecks){
  const charCount={},actionCount={};
  for(const deck of metaDecks){
    for(const c of (deck.characters||[])) charCount[c]=(charCount[c]||0)+1;
    const seen=new Set();
    for(const a of (deck.actions||[])){
      if(!seen.has(a)){actionCount[a]=(actionCount[a]||0)+1;seen.add(a);}
    }
  }
  return{charCount,actionCount};
}

// ── Auto deck (no talent) ─────────────────────────────────────────────────────
export function autoGenerateDeck(cards,cardTags,tags,tagCombos,calcAdjusters=[]){
  const list=Object.values(cards);
  const sc=id=>calcCardScore(id,cardTags,tags,tagCombos,calcAdjusters);
  const chars=list.filter(c=>c.type==='character')
    .sort((a,b)=>sc(b.id)-sc(a.id)).slice(0,3).map(c=>c.id);
  const actions=[];const cnt={};
  const add=id=>{ if(actions.length>=30||(cnt[id]||0)>=2) return; actions.push(id); cnt[id]=(cnt[id]||0)+1; };
  list.filter(c=>c.type!=='character'&&c.type!=='talent')
    .sort((a,b)=>sc(b.id)-sc(a.id))
    .forEach(c=>{ add(c.id); add(c.id); });
  return{chars,actions};
}

// ── Deck constraints ──────────────────────────────────────────────────────────
export function isLegendCard(card){
  return Array.isArray(card?.cost)&&card.cost.some(c=>c.cost_type==='GCG_COST_LEGEND');
}
export function isGensoHenkan(card){ return card?.name?.includes('元素変幻')??false; }
