// cardTags = { [cardId]: string[] }  (duplicates allowed)
// tags      = [{ id, name, score, groupId }]
// tagCombos = [{ id, triggerTag, conditionTag, targetTag, overrideScore, scope:'deck'|'card' }]

function buildScoreMap(tags){
  const m={};
  for(const t of tags) m[t.name]=t.score;
  return m;
}

function applyCombos(effectiveScores, tagSet, combos){
  for(const c of combos){
    if(tagSet.has(c.triggerTag)&&tagSet.has(c.conditionTag)){
      effectiveScores[c.targetTag]=c.overrideScore;
    }
  }
}

// ── Card score (card-local combos applied) ────────────────────────────────────
export function calcCardScore(cardId, cardTags, tags, tagCombos=[]){
  const myTags=cardTags[cardId]||[];
  const myTagSet=new Set(myTags);
  const eff={...buildScoreMap(tags)};
  const localCombos=tagCombos.filter(c=>c.scope==='card');
  applyCombos(eff, myTagSet, localCombos);
  return myTags.reduce((s,n)=>s+(eff[n]??0),0);
}

// ── Deck score (deck-wide combos applied) ─────────────────────────────────────
export function calcDeckScore(chars, actions, cardTags, tags, tagCombos=[]){
  const allIds=[...chars,...actions];
  const allInstances=allIds.flatMap(id=>cardTags[id]||[]);
  const deckTagSet=new Set(allInstances);
  const eff={...buildScoreMap(tags)};
  // scope 'deck' (or undefined = legacy → treat as deck)
  const deckCombos=tagCombos.filter(c=>c.scope==='deck'||!c.scope);
  applyCombos(eff, deckTagSet, deckCombos);
  return allInstances.reduce((s,n)=>s+(eff[n]??0),0);
}

// ── Active deck-wide combo details (for UI display) ───────────────────────────
export function getActiveComboDetails(chars, actions, cardTags, tags, tagCombos=[]){
  const allInstances=[...chars,...actions].flatMap(id=>cardTags[id]||[]);
  const deckTagSet=new Set(allInstances);
  const base=buildScoreMap(tags);
  return tagCombos
    .filter(c=>(c.scope==='deck'||!c.scope)&&deckTagSet.has(c.triggerTag)&&deckTagSet.has(c.conditionTag))
    .map(c=>({...c,baseScore:base[c.targetTag]??0}));
}

// ── Meta analytics ────────────────────────────────────────────────────────────
export function getMetaAnalytics(metaDecks){
  const charCount={},actionCount={};
  for(const deck of metaDecks){
    for(const c of (deck.characters||[])) charCount[c]=(charCount[c]||0)+1;
    const seen=new Set();
    for(const a of (deck.actions||[])){
      if(!seen.has(a)){actionCount[a]=(actionCount[a]||0)+1;seen.add(a);}
    }
  }
  return{charCount,actionCount};
}

// ── Auto deck generation (no talents) ────────────────────────────────────────
export function autoGenerateDeck(cards, cardTags, tags, tagCombos){
  const cardList=Object.values(cards);
  const score=id=>calcCardScore(id,cardTags,tags,tagCombos);

  const chars=cardList.filter(c=>c.type==='character')
    .sort((a,b)=>score(b.id)-score(a.id)).slice(0,3).map(c=>c.id);

  const actions=[];
  const cnt={};
  const add=id=>{
    if(actions.length>=30||(cnt[id]||0)>=2) return false;
    actions.push(id); cnt[id]=(cnt[id]||0)+1; return true;
  };

  // Top-scored non-character, non-talent cards
  const candidates=cardList
    .filter(c=>c.type!=='character'&&c.type!=='talent')
    .sort((a,b)=>score(b.id)-score(a.id));

  for(const card of candidates){
    if(actions.length>=30) break;
    add(card.id); add(card.id);
  }
  return{chars,actions};
}

// ── Helpers for deck constraints ──────────────────────────────────────────────
export function isLegendCard(card){
  if(!card?.cost||!Array.isArray(card.cost)) return false;
  return card.cost.some(c=>c.cost_type==='GCG_COST_LEGEND');
}
export function isGensoHenkan(card){
  return card?.name?.includes('元素変幻')??false;
}